### ISSUE TITLE
Декодирование пользовательских данных в мэпу

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_Joblessness#1]
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/439b60b4ff8b9a9fdded1d54410c4b254790d751/resume.go#L46-L60

https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/439b60b4ff8b9a9fdded1d54410c4b254790d751/resume.go#L113-L126

У вас же есть структура `Summary`, зачем декодировать в мэпу, а потом создавать экземпляр Summary из значений мэпы, если можно сразу декордировать в экземпляр Summary?

**Comment by huvalk** [comment]
Заменено
