### ISSUE TITLE
Разыменование указателя на структуру

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_Joblessness#10]
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/222c5f191392103140f971cbccfced6f7f7bff9f/resume.go#L153

Чтобы получить доступ к полю структуры с помощью указателя на экземпляр этой структуре, не нужно этот указатель разыменовывать. `(*summary).UserID` эквивалентно `summary.UserID`

> Go provide an easy alternative syntax to access fields. **We can access the fields of a struct pointer without dereferencing it first**. Go will take care of dereferencing a pointer under the hood.     

[Подробнее](https://medium.com/rungo/structures-in-go-76377cc106a2)

Аналогично 
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/da74aaa80ad33daab58d5f2e5126ac201008d67f/user_page.go#L48
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/da74aaa80ad33daab58d5f2e5126ac201008d67f/user_page.go#L100
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/da74aaa80ad33daab58d5f2e5126ac201008d67f/user_page.go#L114
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/da74aaa80ad33daab58d5f2e5126ac201008d67f/user_page.go#L115
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/da74aaa80ad33daab58d5f2e5126ac201008d67f/user_page.go#L146
и т.д.

**Comment by huvalk** [comment]
Исправлено
