### ISSUE TITLE
Вечная блокировка

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_Joblessness#13]
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/f10b13dfd921bdf81aaff2fc74069f78f6a6db01/resume.go#L213-L220

Выход из функции без разблокировки мьютекса приведет к дедлоку...

Мой вам совет, сделайте getter и setter для чтения/записи из мэпы, чтобы не таскать вызов мьютекса в каждой функции. Это улучшит читаемость кода и сведет на нет вероятность забыть разблокировать мьютекс перед выходом из функции.

**Comment by SmartPhoneJava** [comment]
Число забытых разблокировок множилось...
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/597100f5d4ac5999b86b8be4abb867a59e9fa2d9/handlers/auth.go#L143-L150

https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/597100f5d4ac5999b86b8be4abb867a59e9fa2d9/handlers/auth.go#L171-L176

**Comment by huvalk** [comment]
Исправили
