### ISSUE TITLE
Гонки в SummaryHandler

### ISSUE THREAD

**Issue by SmartPhoneJava** [go-park-mail-ru/2020_1_Joblessness#3]
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/439b60b4ff8b9a9fdded1d54410c4b254790d751/resume.go#L23-L26

Мэпы в голанге не потокобезопасны, поэтому стоит защитить `summaries` с помощью мьютекса. А для счетчика `SummaryId` следует использовать [атомарные](https://golang.org/pkg/sync/atomic/) операции. Однако для этого следует заменить тип `SummaryId`  с `uint` на `uint32`(или uint64)
Тогда вместо 
https://github.com/go-park-mail-ru/2020_1_Joblessness/blob/439b60b4ff8b9a9fdded1d54410c4b254790d751/resume.go#L28-L31
будет 
``` 
func (api *SummaryHandler) getNewSummaryId() uint32 {
	return atomic.AddUint32(&api.SummaryId, 1) 
}
```
и это законно ;)

**Comment by huvalk** [comment]
Исправили в SummaryHandler и VacancyHandler.
